### ISSUE TITLE
Sein breaks Custom Knight mod

### ISSUE THREAD

**Issue by Resseidjer** [dplochcoder/HollowKnight.Sein#7]
[ModLog -sein on.txt](https://github.com/user-attachments/files/16518123/ModLog.-sein.on.txt)
[ModLog -sein off.txt](https://github.com/user-attachments/files/16518122/ModLog.-sein.off.txt)
Attached is loading log with sein and its dependencies and loading log with dependencies only

**Comment by dplochcoder** [comment]
This issue is known and fixed by https://github.com/PrashantMohta/HollowKnight.CustomKnight/pull/45, it is awaiting a new CustomKnight release
